from dotenv import load_dotenv
import os

load_dotenv()

DATABASE_URL: str = os.getenv("DATABASE_URL")
SECRET_KEY: str = os.getenv("SECRET_KEY")
REFRESH_SECRET_KEY: str = os.getenv("REFRESH_SECRET_KEY")
ALGORITHM: str = os.getenv("ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES: int = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES"))
REFRESH_TOKEN_EXPIRE_DAYS: int = int(os.getenv("REFRESH_TOKEN_EXPIRE_DAYS"))
RESET_SECRET_KEY = os.getenv("RESET_SECRET_KEY")
RESET_TOKEN_EXPIRE_MINUTES = int(os.getenv("RESET_TOKEN_EXPIRE_MINUTES"))
CELERY_BROKER_URL: str = os.getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND: str = os.getenv("CELERY_RESULT_BACKEND")
